### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by leswong** [esteban-mallen/homebridge-roomba-stv#20]
Error Loading Plugin

### Expected Behavior
Plugin loads successfully when homebridge starts.

### Current Behavior
Plugin homebridge-roomba-stv does not load.  See fragment of log below.

### Steps to Reproduce (for bugs)
install the plugin:  npm install homebridge-roomba-stv

### Versions
- **Homebridge**: 0.4.45
- **Node**:      6.13.1
- **Plugin**:     1.0.0

### Configuration
```json
"accessories": [
  {
    "accessory": "Roomba",
    "name": "Roomba",
    "model": "960",
    "blid": "3165011492511800",
    "robotpwd": ":1:1542634710:VCHNtwM3Q0RI6Vxd",
    "ipaddress": "192.168.10.101",
    "autoRefreshEnabled": true,
    "keepAliveEnabled": true,
    "cacheTTL": 30
  }
]
```

### Homebridge Log / Command Output
```
Nov 20 00:25:58 ubuntu homebridge[3602]: [11/20/2018, 12:25:58 AM] Loaded config.json with 1 accessories and 2 platforms.
Nov 20 00:25:58 ubuntu homebridge[3602]: [11/20/2018, 12:25:58 AM] ---
Nov 20 00:25:58 ubuntu homebridge[3602]: [11/20/2018, 12:25:58 AM] Loaded plugin: homebridge-config-ui-x
Nov 20 00:25:58 ubuntu homebridge[3602]: [11/20/2018, 12:25:58 AM] Registering platform 'homebridge-config-ui-x.config'
Nov 20 00:25:58 ubuntu homebridge[3602]: [11/20/2018, 12:25:58 AM] ---
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] Loaded plugin: homebridge-homeseer-plugin-2018
Nov 20 00:25:59 ubuntu homebridge[3602]: homebridge API version: 2.2
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] Registering platform 'homebridge-HomeSeerPlatform.HomeSeer'
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] ---
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] ====================
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] ERROR LOADING PLUGIN homebridge-roomba-stv:
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] /usr/lib/node_modules/homebridge-roomba-stv/index.js:75
Nov 20 00:25:59 ubuntu homebridge[3602]:             this.onConnected(roomba, async () => {
Nov 20 00:25:59 ubuntu homebridge[3602]:                                            ^
Nov 20 00:25:59 ubuntu homebridge[3602]: SyntaxError: Unexpected token (
Nov 20 00:25:59 ubuntu homebridge[3602]:     at createScript (vm.js:56:10)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Object.runInThisContext (vm.js:97:10)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Module._compile (module.js:549:28)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Object.Module._extensions..js (module.js:586:10)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Module.load (module.js:494:32)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at tryModuleLoad (module.js:453:12)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Function.Module._load (module.js:445:3)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Module.require (module.js:504:17)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at require (internal/module.js:20:19)
Nov 20 00:25:59 ubuntu homebridge[3602]:     at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:23)
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] ====================
Nov 20 00:25:59 ubuntu homebridge[3602]: [11/20/2018, 12:25:59 AM] Loading 2 platforms...
```

**Comment by esteban-mallen** [comment]
Please try updating your node version
