### ISSUE TITLE
Can't run getrobotpwd

### ISSUE THREAD

**Issue by siobhanellis** [esteban-mallen/homebridge-roomba-stv#46]
When running getrobotpwd (With the correct IP address), I get:

> homebridge-roomba-stv@1.5.0 getrobotpwd /usr/local/lib/node_modules/homebridge-roomba-stv
> cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.162"

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.8.0 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

audited 1281 packages in 2.951s
found 2 vulnerabilities (1 low, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.162:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-roomba-stv@1.5.0 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.162"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-roomba-stv@1.5.0 getrobotpwd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/siobhan/.npm/_logs/2019-11-30T02_59_25_146Z-debug.log

The log file says:

1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'getrobotpwd',
1 verbose cli   '192.168.1.162'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.1.0
4 verbose run-script [ 'pregetrobotpwd', 'getrobotpwd', 'postgetrobotpwd' ]
5 info lifecycle homebridge-roomba-stv@1.5.0~pregetrobotpwd: homebridge-roomba-stv@1.5.0
6 info lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: homebridge-roomba-stv@1.5.0
7 verbose lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: unsafe-perm in lifecycle true
8 verbose lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/homebridge-roomba-stv/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/npm_packages/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: CWD: /usr/local/lib/node_modules/homebridge-roomba-stv
10 silly lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cd node_modules/dorita980 && npm install && ' +
10 silly lifecycle     'node ./bin/getpassword.js "192.168.1.162"'
10 silly lifecycle ]
11 silly lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: Returned: code: 1  signal: null
12 info lifecycle homebridge-roomba-stv@1.5.0~getrobotpwd: Failed to exec getrobotpwd script
13 verbose stack Error: homebridge-roomba-stv@1.5.0 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.162"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid homebridge-roomba-stv@1.5.0
15 verbose cwd /usr/local/lib/node_modules/homebridge-roomba-stv
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/bin/npm" "run" "getrobotpwd" "192.168.1.162"
18 verbose node v12.1.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error homebridge-roomba-stv@1.5.0 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.162"`
22 error Exit status 1
23 error Failed at the homebridge-roomba-stv@1.5.0 getrobotpwd script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by siobhanellis** [comment]
obviously it is having problems getting through to the robot.

1) The home bridge server (Mac mini) and the robot are on the same wifi network, and it is 2.4Ghz only.
2) When I look at the robot info in the Roomba app, it tells me it is on the correct network and I have the correct IP address.
3) I can't seem to ping the address, but that may be turned off anyway.
4) I can run the Roomba from the app, no problem.

**Comment by siobhanellis** [comment]
ignore this. Typo on the IP address, even though I kept checking. argh!
